"""Static configuration: which files we index, which we refuse to.

No logic lives here — only data. walker.py imports these constants; nothing
else should need to. Changing indexing policy means editing THIS file only.
"""

# ---------------------------------------------------------------------------
# Language classification (L0).
#
# Maps file extension -> language key. The language key is used twice:
#   1. parsers.get_parser(key)  -> which tree-sitter grammar to load
#   2. extract.EXTRACTORS[key]  -> which symbol extractor to run
#
# ".tsx" gets its own key because it needs a DIFFERENT GRAMMAR (JSX syntax
# is ambiguous with TS generics — `<T>` could open a tag or a type param —
# so tree-sitter ships two grammars). The extractor is shared: tsx node
# types are a superset of typescript's, so the same queries work on both.
# ---------------------------------------------------------------------------
LANGUAGE_BY_EXTENSION: dict[str, str] = {
    ".py": "python",
    ".pyi": "python",       # stub files: pure signatures, great symbol data
    ".go": "go",
    ".ts": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".tsx": "tsx",
}

# ---------------------------------------------------------------------------
# Directories never worth descending into. walker.iter_source_files() prunes
# these IN-PLACE during os.walk, so we never even stat their contents —
# this single list is why indexing a repo with node_modules doesn't take
# ten minutes. Roadmap: "excludes 60-90% of files".
# ---------------------------------------------------------------------------
EXCLUDED_DIRS: frozenset[str] = frozenset({
    # VCS / tooling internals
    ".git", ".hg", ".svn",
    # dependency trees (the big win)
    "node_modules", "vendor", "third_party", "thirdparty", "bower_components",
    # virtualenvs / caches
    ".venv", "venv", "env", "__pycache__", ".tox", ".nox",
    ".mypy_cache", ".pytest_cache", ".ruff_cache",
    # build output
    "dist", "build", "out", "target", ".next", ".nuxt", "coverage",
    # Go convention: fixture data for tests, often intentionally unparseable
    "testdata",
})

# ---------------------------------------------------------------------------
# Generated-file detection. Checked against the FIRST 1KB only — every
# generator convention puts its marker at the top (Go's convention is even
# codified: `^// Code generated .* DO NOT EDIT\.$`). Heuristic, not proof:
# a hand-written file quoting "DO NOT EDIT" gets skipped. Acceptable — a
# false skip costs a few symbols; indexing 40k lines of protobuf output
# costs signal everywhere else.
# ---------------------------------------------------------------------------
GENERATED_MARKERS: tuple[str, ...] = (
    "Code generated by",     # Go convention (protoc-gen-go, mockgen, stringer)
    "DO NOT EDIT",           # universal
    "@generated",            # Facebook/Meta convention
    "<auto-generated",       # .NET-style, appears in some TS output
    "Autogenerated",
    "This file is automatically generated",
)
GENERATED_SNIFF_BYTES = 1024   # how much of the head we scan for markers

# Files larger than this are almost always generated, vendored, or data
# masquerading as code. 2 MB of hand-written source in one file basically
# does not exist in the wild.
MAX_FILE_BYTES = 2 * 1024 * 1024

# ---------------------------------------------------------------------------
# Test-file detection. We STILL INDEX test files (their symbols are real),
# we just flag them: Day 3's test->source mapping (`wi tests-for`) is built
# on this flag, and `wi symbols` can filter them out of results.
# Patterns are matched by walker._looks_like_test().
# ---------------------------------------------------------------------------
TEST_DIR_NAMES: frozenset[str] = frozenset({"tests", "test", "__tests__", "e2e"})
