"""End-to-end: synthetic multi-language repo -> index_repository -> query DB.

This is the test that exercises the REAL pipeline — walker feeding parser
feeding extractors feeding SQLite — exactly as `wi index` does.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from wright_index.db import Database
from wright_index.indexer import index_repository


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A tiny three-language repo with one skip case and one broken file."""
    (tmp_path / "app").mkdir()
    (tmp_path / "app" / "main.py").write_text(
        'def main():\n    """Entry."""\n    return 0\n\n'
        'class App:\n    def run(self):\n        pass\n',
        encoding="utf-8")
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "dev.go").write_text(
        'package pkg\n\n'
        '// Device is a device.\n'
        'type Device struct{}\n\n'
        'func (d *Device) Reset() error { return nil }\n',
        encoding="utf-8")
    (tmp_path / "web").mkdir()
    (tmp_path / "web" / "api.ts").write_text(
        'export interface Opts { a: string }\n'
        'export const call = (o: Opts) => o.a;\n',
        encoding="utf-8")
    # a generated file: must be recorded as skipped, contribute no symbols
    (tmp_path / "pkg" / "gen.go").write_text(
        '// Code generated by mockgen. DO NOT EDIT.\npackage pkg\n',
        encoding="utf-8")
    # a syntactically broken file: must still index what parses (error-tolerance)
    (tmp_path / "app" / "broken.py").write_text(
        'def fine():\n    pass\n\ndef broken(:\n', encoding="utf-8")
    return tmp_path


def test_end_to_end_counts(repo: Path, tmp_path: Path):
    db_path = tmp_path / "idx.db"
    result = index_repository(repo, db_path=db_path)

    assert result.files_indexed == 4                    # main.py dev.go api.ts broken.py
    assert result.files_skipped == 1                    # gen.go
    assert result.skipped_by_reason == {"generated": 1}
    assert result.parse_errors == 1                     # broken.py
    assert result.symbol_count >= 7                     # across three languages


def test_symbols_queryable_after_indexing(repo: Path, tmp_path: Path):
    db_path = tmp_path / "idx.db"
    index_repository(repo, db_path=db_path)

    db = Database(db_path)
    # --file suffix match, the `wi symbols --file` path
    rows = db.search_symbols(file="dev.go")
    qnames = {r["qualified_name"] for r in rows}
    assert qnames == {"Device", "Device.Reset"}

    # kind filter
    structs = db.search_symbols(kind="struct")
    assert [r["name"] for r in structs] == ["Device"]

    # error-tolerant parsing: broken.py's intact function is still there
    fine = db.search_symbols(file="broken.py")
    assert "fine" in {r["name"] for r in fine}
    db.close()


def test_reindex_is_rebuild_not_append(repo: Path, tmp_path: Path):
    """Day 1 contract: running index twice must not duplicate rows."""
    db_path = tmp_path / "idx.db"
    r1 = index_repository(repo, db_path=db_path)
    r2 = index_repository(repo, db_path=db_path)
    assert r1.symbol_count == r2.symbol_count

    db = Database(db_path)
    n = db.conn.execute("SELECT COUNT(*) AS n FROM symbols").fetchone()["n"]
    assert n == r2.symbol_count
    db.close()


def test_meta_recorded(repo: Path, tmp_path: Path):
    db_path = tmp_path / "idx.db"
    index_repository(repo, db_path=db_path)
    db = Database(db_path)
    assert db.get_meta("repo_root") == str(repo.resolve())
    assert db.get_meta("indexed_at") is not None
    assert db.get_meta("schema_version") == "1"
    db.close()
