"""L0 tests — the walker's include/exclude/flag decisions.

Strategy: build a tiny synthetic repo in tmp_path, walk it, assert on the
classification decisions. No parsing involved at this layer.
"""

from __future__ import annotations

from pathlib import Path

from wright_index.walker import iter_source_files


def _write(root: Path, rel: str, content: str = "x = 1\n") -> None:
    """Create a file (and parents) under the fake repo."""
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def _walk(root: Path) -> dict:
    """Run the walker, key results by rel_path for easy assertions."""
    return {sf.rel_path: sf for sf in iter_source_files(root)}


def test_classifies_languages(tmp_path: Path):
    _write(tmp_path, "a.py")
    _write(tmp_path, "b.go", "package main\n")
    _write(tmp_path, "c.ts", "const x = 1\n")
    _write(tmp_path, "d.tsx", "const x = 1\n")
    _write(tmp_path, "notes.md", "# not code\n")          # ignored entirely

    files = _walk(tmp_path)
    assert files["a.py"].language == "python"
    assert files["b.go"].language == "go"
    assert files["c.ts"].language == "typescript"
    assert files["d.tsx"].language == "tsx"               # separate grammar key
    assert "notes.md" not in files                        # unknown ext -> not yielded


def test_prunes_excluded_and_hidden_dirs(tmp_path: Path):
    _write(tmp_path, "src/ok.py")
    _write(tmp_path, "node_modules/lib/index.ts")          # dependency tree
    _write(tmp_path, "vendor/pkg/x.go", "package pkg\n")   # go vendoring
    _write(tmp_path, ".github/workflows/x.py")             # hidden dir

    files = _walk(tmp_path)
    assert list(files) == ["src/ok.py"]                    # everything else pruned


def test_generated_file_recorded_but_skipped(tmp_path: Path):
    _write(tmp_path, "gen.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n")

    sf = _walk(tmp_path)["gen.go"]
    assert sf.skipped_reason == "generated"
    assert sf.content is None                              # never parsed
    assert sf.content_hash                                 # but still hashed (Day 5)


def test_oversized_file_skipped_without_reading(tmp_path: Path):
    big = tmp_path / "big.py"
    big.write_bytes(b"#" + b"x" * (2 * 1024 * 1024 + 10))  # just over MAX_FILE_BYTES

    sf = _walk(tmp_path)["big.py"]
    assert sf.skipped_reason == "too_large"


def test_binary_masquerading_as_source_skipped(tmp_path: Path):
    (tmp_path / "fake.py").write_bytes(b"\x00\x01\x02binary")

    sf = _walk(tmp_path)["fake.py"]
    assert sf.skipped_reason == "binary"


def test_test_files_flagged_not_excluded(tmp_path: Path):
    _write(tmp_path, "pkg/device.go", "package pkg\n")
    _write(tmp_path, "pkg/device_test.go", "package pkg\n")
    _write(tmp_path, "tests/test_app.py")
    _write(tmp_path, "src/Button.spec.tsx", "const x = 1\n")

    files = _walk(tmp_path)
    assert not files["pkg/device.go"].is_test
    assert files["pkg/device_test.go"].is_test             # go convention
    assert files["tests/test_app.py"].is_test              # dir + prefix
    assert files["src/Button.spec.tsx"].is_test            # .spec.
    # flagged but still yielded WITH content — tests get indexed
    assert files["pkg/device_test.go"].content is not None


def test_content_hash_is_stable_sha256(tmp_path: Path):
    _write(tmp_path, "a.py", "x = 1\n")
    h1 = _walk(tmp_path)["a.py"].content_hash
    h2 = _walk(tmp_path)["a.py"].content_hash
    assert h1 == h2 and len(h1) == 64                      # sha256 hex digest
